Controllers/DepartmentsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.BL.Interfaces;
using WebApp.BL.Models;
using WebApp.DAL.Entity;

namespace WebApp.Controllers
{
    public class DepartmentsController : Controller
    {

        #region Fields
        private readonly IDepartmentsRepo departments;
        private readonly IMapper mapper;
        #endregion
        #region Constructor
        public DepartmentsController(IDepartmentsRepo departments, IMapper mapper)
        {
            this.departments = departments;
            this.mapper = mapper;
        }
        #endregion
        #region Actions
        public IActionResult Index(string SearchValue = null)
        {
            if (SearchValue == null || SearchValue == "")
            {
                var data = departments.Get();
                var result = mapper.Map<IEnumerable<DepartmentsVM>>(data);
                return View(result);
            }
            else
            {
                var data = departments.SearchByName(SearchValue);
                var result = mapper.Map<IEnumerable<DepartmentsVM>>(data);
                return View(result);
            }

        }
        public IActionResult Details(int id)
        {

            var data = departments.GetByID(id);
            var result = mapper.Map<DepartmentsVM>(data);
            return View(result);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(DepartmentsVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = mapper.Map<Departments>(model);
                    departments.Create(data);
                    return RedirectToAction("Index");
                }
                return View();

            }
            catch (Exception)
            {
                return View();
            }

        }
        public IActionResult Edit(int id)
        {

            var data = departments.GetByID(id);
            var result = mapper.Map<DepartmentsVM>(data);
            return View(result);
        }
        [HttpPost]
        public IActionResult Edit(DepartmentsVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = mapper.Map<Departments>(model);
                    departments.Edit(data);
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (Exception)
            {
                return View();
            }
        }
        public IActionResult Delete(int id)
        {

            var data = departments.GetByID(id);
            var result = mapper.Map<DepartmentsVM>(data);
            return View(result);
        }
        [HttpPost]
        public IActionResult Delete(DepartmentsVM model)
        {
            try
            {
                var oldData = departments.GetByID(model.Id);
                departments.Delete(oldData);
                return RedirectToAction("Index");

            }
            catch (Exception)
            {
                return View();
            }

        }
        #endregion


    }
}

Views/Departments/Create.cshtml
@model WebApp.BL.Models.DepartmentsVM
@section Search
{

    <form class="form-inline my-2 my-lg-0 mr-lg-2">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for...">
            <span class="input-group-btn">
                <button class="btn btn-primary" type="button">
                    <i class="fa fa-search"></i>
                </button>
            </span>
        </div>
    </form>
}



<div class="d-flex flex-column  align-items-center justify-content-center">
    <h2 class="my-3 my-sm-5">Add new department</h2>
    <form class="form-group w-75 " asp-action="Create" asp-controller="Departments">



        <div class="form-group row">
            <label asp-for="DepartmentName" class="col-sm-2 col-form-label font-weight-bold">Department name</label>
            <div class="col-sm-10">
                <input type="text" asp-for="DepartmentName" class="form-control ">
                <div class=" text-danger mt-2">
                    <span asp-validation-for="DepartmentName" class="form-control-feedback"></span>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="DepartmentCode" class="col-sm-2 col-form-label font-weight-bold">Department code</label>
            <div class="col-sm-10">
                <input type="text" asp-for="DepartmentCode" class="form-control ">
                <div class=" text-danger mt-2">
                    <span asp-validation-for="DepartmentCode" class="form-control-feedback"></span>
                </div>
            </div>
        </div>

       
       
            <input type="submit" value="Add" class="btn btn-primary form-control mb-3">
            <input type="reset" value="Cancel" class="btn btn-danger form-control">
       
    </form>



    @section Validation{
        <script src="~/vendor/jquery-validate/jquery.validate.min.js"></script>
        <script src="~/vendor/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    }



</div>

Views/Departments/Delete.cshtml
@model WebApp.BL.Models.DepartmentsVM

@section Search
{

    <form class="form-inline my-2 my-lg-0 mr-lg-2">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for...">
            <span class="input-group-btn">
                <button class="btn btn-primary" type="button">
                    <i class="fa fa-search"></i>
                </button>
            </span>
        </div>
    </form>
}

<div class="d-flex flex-column  align-items-center justify-content-center">
    <h2 class="my-3 my-sm-5">Delete department</h2>
    <form class="form-group w-75 " asp-controller="Departments" asp-action="Delete">


        <div class="form-group row">
            <label asp-for="DepartmentName" class="col-sm-2 col-form-label font-weight-bold">Department name</label>
            <div class="col-sm-10">
                <input type="text" asp-for="DepartmentName"disabled class="form-control ">
                <div class=" text-danger mt-2">
                    
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="DepartmentCode" class="col-sm-2 col-form-label font-weight-bold">Department code</label>
            <div class="col-sm-10">
                <input type="text" asp-for="DepartmentCode" disabled class="form-control ">
                <div class=" text-danger mt-2">
                    
                </div>
            </div>
        </div>



       
            <button type="button" data-toggle="modal" data-target="#exampleModal" class="form-control btn btn-danger mb-3">Delete</button>
            <button asp-action="Index" asp-controller="Departments" class="form-control btn btn-primary mb-3 ">Back To Departments</button>
     

        <!-- Modal -->

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body text-center">
                        <p>
                            You want to delete a department. <br />
                            Are you sure?
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </div>
            </div>
        </div>




    </form>
</div>

Views/Departments/Details.cshtml
@model WebApp.BL.Models.DepartmentsVM
@section Search
{

    <form class="form-inline my-2 my-lg-0 mr-lg-2">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for...">
            <span class="input-group-btn">
                <button class="btn btn-primary" type="button">
                    <i class="fa fa-search"></i>
                </button>
            </span>
        </div>
    </form>
}


<div class="d-flex flex-column  align-items-center">
    <h2 class="my-3 my-sm-5">Department details</h2>
    <form class="form-group w-75 ">


        <div class="form-group row">
            <label asp-for="DepartmentName" class="col-sm-2 col-form-label font-weight-bold">Department name</label>
            <div class="col-sm-10">
                <input type="text" asp-for="DepartmentName" disabled class="form-control ">
                <div class=" text-danger mt-2">

                </div>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="DepartmentCode" class="col-sm-2 col-form-label font-weight-bold">Department code</label>
            <div class="col-sm-10">
                <input type="text" asp-for="DepartmentCode" disabled class="form-control ">
                <div class=" text-danger mt-2">

                </div>
            </div>
        </div>



        <button asp-action="Edit" asp-controller="Departments" asp-route-id="@Model.Id" class="btn btn-warning text-white form-control mb-3">Edit</button>
        <button asp-action="Delete" asp-controller="Departments" asp-route-id="@Model.Id" class="btn btn-danger text-white form-control mb-3">Delete</button>
        <button asp-action="Index" asp-controller="Departments" class="btn btn-primary form-control mb-3">Back To Departments</button>


    </form>
</div>

Views/Departments/Edit.cshtml
@model WebApp.BL.Models.DepartmentsVM

@section Search
{

    <form class="form-inline my-2 my-lg-0 mr-lg-2">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for...">
            <span class="input-group-btn">
                <button class="btn btn-primary" type="button">
                    <i class="fa fa-search"></i>
                </button>
            </span>
        </div>
    </form>
}


<div class="d-flex flex-column  align-items-center justify-content-center">
    <h2 class="my-3 my-sm-5">Update department</h2>
    <form class="form-group w-75 " asp-action="Index" asp-controller="Departments">


        <div class="form-group row">
            <label asp-for="DepartmentName" class="col-sm-2 col-form-label font-weight-bold">Department name</label>
            <div class="col-sm-10">
                <input type="text" asp-for="DepartmentName" class="form-control ">
                <div class=" text-danger mt-2">
                    <span asp-validation-for="DepartmentName" class="form-control-feedback"></span>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="DepartmentCode" class="col-sm-2 col-form-label font-weight-bold">Department code</label>
            <div class="col-sm-10">
                <input type="text" asp-for="DepartmentCode" class="form-control ">
                <div class=" text-danger mt-2">
                    <span asp-validation-for="DepartmentCode" class="form-control-feedback"></span>
                </div>
            </div>
        </div>

        <input type="submit" value="Update" class="btn btn-primary form-control  mb-2">
        <button asp-action="Index" asp-controller="Departments" class="btn btn-danger form-control ">Cancel</button>
    </form>



    @section Validation{
        <script src="~/vendor/jquery-validate/jquery.validate.min.js"></script>
        <script src="~/vendor/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    }



</div>

Views/Departments/Index.cshtml
@model IEnumerable<WebApp.BL.Models.DepartmentsVM>

@section Search 
{

    <form class="form-inline my-2 my-lg-0 mr-lg-2" asp-action="Index" asp-controller="Departments">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for department ..." name="SearchValue">
            <span class="input-group-btn">
                <button class="btn btn-primary" type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </span>
        </div>
    </form>
}

<div class="container-fluid mb-3">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-action="Index" asp-controller="Home">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Tables /  Departments Table</li>
    </ol>
    <!-- Example DataTables Card-->
    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-table"></i> Departments table
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Department name</th>
                            <th>Department code</th>
                            <th>Details</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Department name</th>
                            <th>Department code</th>
                            <th>Details</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.DepartmentName</td>
                                <td>@item.DepartmentCode</td>
                                <td><a asp-controller="Departments" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Details</a></td>
                                <td><a asp-action="Edit" asp-controller="Departments" asp-route-id="@item.Id" class="btn btn-warning text-white">Edit</a></td>
                                <td><a  asp-action="Delete" asp-controller="Departments" asp-route-id="@item.Id" class="btn btn-danger text-white">Delete</a></td>

                            </tr>

 
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">

            <a asp-action="Create" asp-controller="Departments" class=" btn btn-primary float-right">Add department</a>

        </div>
    </div>
</div>